const express = require('express');
const { auth, requireRole } = require('../middleware/auth');
const Client = require('../models/Client');
const Assignment = require('../models/Assignment');
const Note = require('../models/Note');
const Appointment = require('../models/Appointment');

const router = express.Router();

// GET /api/clients/:clientId
router.get('/:clientId', auth, requireRole('supervisor'), async (req, res) => {
  try {
    const client = await Client.findById(req.params.clientId);
    if (!client) return res.status(404).json({ message: 'Client not found' });
    res.json({ success: true, data: { client } });
  } catch (err) {
    console.error('Get client error:', err);
    res.status(500).json({ message: 'Failed to fetch client' });
  }
});

// GET /api/clients/:clientId/shifts
router.get('/:clientId/shifts', auth, requireRole('supervisor'), async (req, res) => {
  try {
    const assignments = await Assignment.find({ clientId: req.params.clientId })
      .populate('staffId', 'name email')
      .sort({ startDate: -1 });
    res.json({ success: true, data: assignments });
  } catch (err) {
    console.error('Get client shifts error:', err);
    res.status(500).json({ message: 'Failed to fetch shifts' });
  }
});

// GET /api/clients/:clientId/notes
router.get('/:clientId/notes', auth, requireRole('supervisor'), async (req, res) => {
  try {
    const notes = await Note.find({ clientId: req.params.clientId })
      .populate('staffId', 'name')
      .sort({ createdAt: -1 });
    res.json({ success: true, data: notes });
  } catch (err) {
    console.error('Get client notes error:', err);
    res.status(500).json({ message: 'Failed to fetch notes' });
  }
});

// GET /api/clients/:clientId/summary-report
router.get('/:clientId/summary-report', auth, requireRole('supervisor'), async (req, res) => {
  try {
    const client = await Client.findById(req.params.clientId);
    if (!client) return res.status(404).json({ message: 'Client not found' });

    const [assignments, notes, appointments] = await Promise.all([
      Assignment.find({ clientId: req.params.clientId }).populate('staffId', 'name').sort({ startDate: -1 }),
      Note.find({ clientId: req.params.clientId }).populate('staffId', 'name').sort({ createdAt: -1 }),
      Appointment.find({ clientId: req.params.clientId }).sort({ date: -1 })
    ]);

    const report = [
      `CLIENT SUMMARY REPORT`,
      `======================`,
      `Name:              ${client.name}`,
      `NDIS Number:       ${client.ndisNumber || 'N/A'}`,
      `Date of Birth:     ${client.dateOfBirth ? new Date(client.dateOfBirth).toLocaleDateString('en-AU') : 'N/A'}`,
      `Care Level:        ${client.careLevel}`,
      `Phone:             ${client.phone || 'N/A'}`,
      `Email:             ${client.email || 'N/A'}`,
      `Address:           ${client.address || 'N/A'}`,
      `Room:              ${client.room || 'N/A'}`,
      `Emergency Contact: ${client.emergencyContact || 'N/A'}`,
      ``,
      `SHIFTS (${assignments.length} total)`,
      `---------`,
      ...assignments.slice(0, 10).map(a =>
        `  ${new Date(a.startDate).toLocaleDateString('en-AU')} | ${a.shift} | ${a.staffId?.name || 'Unknown'}`
      ),
      ``,
      `NOTES (${notes.length} total)`,
      `------`,
      ...notes.slice(0, 10).map(n =>
        `  ${new Date(n.createdAt).toLocaleDateString('en-AU')} | ${n.status} | ${n.staffId?.name || 'Unknown'}`
      ),
      ``,
      `APPOINTMENTS (${appointments.length} total)`,
      `-------------`,
      ...appointments.slice(0, 10).map(a =>
        `  ${new Date(a.date).toLocaleDateString('en-AU')} | ${a.title} | ${a.status}`
      ),
      ``,
      `--- Generated by NexCare on ${new Date().toLocaleDateString('en-AU')} ---`
    ].join('\n');

    res.setHeader('Content-Type', 'application/octet-stream');
    res.setHeader('Content-Disposition', `attachment; filename="${client.name}-Summary-Report.txt"`);
    res.send(report);
  } catch (err) {
    console.error('Summary report error:', err);
    res.status(500).json({ message: 'Failed to generate report' });
  }
});

module.exports = router;
