const express = require('express');
const { auth } = require('../middleware/auth');
const Note = require('../models/Note');

const router = express.Router();

// Simple text analysis helper
function analyzeText(text) {
  if (!text || !text.trim()) {
    return { summary: 'No content available for analysis.', keywords: [], sentiment: 'Neutral' };
  }

  // Summary: first 300 chars
  const summary = text.length > 300 ? text.slice(0, 297) + '...' : text;

  // Keywords: extract meaningful words (4+ chars, not stop words)
  const stopWords = new Set([
    'that', 'this', 'with', 'have', 'from', 'they', 'will', 'been', 'were',
    'said', 'each', 'which', 'their', 'there', 'what', 'when', 'where', 'also',
    'into', 'about', 'after', 'then', 'than', 'some', 'more', 'very', 'just',
    'would', 'could', 'should', 'client', 'staff', 'shift', 'note', 'today'
  ]);
  const wordFreq = {};
  text.toLowerCase().match(/\b[a-z]{4,}\b/g)?.forEach(word => {
    if (!stopWords.has(word)) wordFreq[word] = (wordFreq[word] || 0) + 1;
  });
  const keywords = Object.entries(wordFreq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([word]) => word.charAt(0).toUpperCase() + word.slice(1));

  // Sentiment: simple keyword matching
  const positiveWords = ['well', 'good', 'happy', 'calm', 'stable', 'improved', 'positive', 'comfortable', 'cooperative', 'engaged', 'progress', 'better', 'great', 'assist', 'independent'];
  const negativeWords = ['refused', 'agitated', 'distressed', 'fall', 'pain', 'declined', 'concern', 'issue', 'problem', 'difficult', 'worse', 'anxious', 'upset', 'unwell', 'incident'];
  const lowerText = text.toLowerCase();
  const posScore = positiveWords.filter(w => lowerText.includes(w)).length;
  const negScore = negativeWords.filter(w => lowerText.includes(w)).length;
  const sentiment = negScore > posScore ? 'Concerns noted — review recommended' :
                    posScore > negScore ? 'Positive — client appears to be doing well' :
                    'Neutral — routine care documented';

  return { summary, keywords, sentiment };
}

// POST /api/notes/:noteId/analyze
router.post('/:noteId/analyze', auth, async (req, res) => {
  try {
    const note = await Note.findById(req.params.noteId);
    if (!note) return res.status(404).json({ message: 'Note not found' });

    const allText = (note.entries || [])
      .map(e => e.content || '')
      .filter(c => !c.startsWith('File upload:') && !c.includes('image uploaded'))
      .join(' ');

    const analysis = analyzeText(allText);
    res.json({ success: true, data: analysis });
  } catch (err) {
    console.error('Analyze error:', err);
    res.status(500).json({ message: 'Analysis failed' });
  }
});

// GET /api/notes/:noteId/analysis-report
router.get('/:noteId/analysis-report', auth, async (req, res) => {
  try {
    const note = await Note.findById(req.params.noteId).populate('clientId', 'name').populate('staffId', 'name');
    if (!note) return res.status(404).json({ message: 'Note not found' });

    const allText = (note.entries || [])
      .map(e => e.content || '')
      .filter(c => !c.startsWith('File upload:') && !c.includes('image uploaded'))
      .join(' ');

    const analysis = analyzeText(allText);

    const report = [
      'CLINICAL NOTE ANALYSIS REPORT',
      '==============================',
      `Client: ${note.clientId?.name || 'Unknown'}`,
      `Staff:  ${note.staffId?.name || 'Unknown'}`,
      `Date:   ${new Date(note.shiftDate || note.createdAt).toLocaleDateString('en-AU', { timeZone: 'Australia/Sydney' })}`,
      `Shift:  ${note.shift || 'N/A'}`,
      '',
      'SUMMARY',
      '-------',
      analysis.summary,
      '',
      'KEYWORDS',
      '--------',
      analysis.keywords.join(', ') || 'None identified',
      '',
      'SENTIMENT',
      '---------',
      analysis.sentiment,
      '',
      '--- Generated by NexCare ---'
    ].join('\n');

    res.setHeader('Content-Type', 'application/octet-stream');
    res.setHeader('Content-Disposition', `attachment; filename="analysis-${req.params.noteId}.txt"`);
    res.send(report);
  } catch (err) {
    console.error('Report error:', err);
    res.status(500).json({ message: 'Report generation failed' });
  }
});

module.exports = router;
